import type { MetadataRoute } from "next";
import { SITE_URL } from "@/lib/seo/site";

/**
 * robots.txt dinâmico — aponta sitemap canônico e bloqueia apps autenticados.
 * Áreas públicas (/, /clinicas, /plans, /psychologists, /faq, /blog…) ficam indexáveis.
 */
const DISALLOW = [
  "/api/",
  "/dashboard/",
  "/diary/",
  "/care/",
  "/clinic/",
  "/teleconsulta/",
  "/assinatura/",
  "/assistente/",
  "/suporte/",
  "/org-invite",
  "/login",
  "/register",
  "/forgot-password",
  "/reset-password",
  "/verify-email",
  "/aguardando-verificacao",
  "/care-invite",
  "/campanha",
  "/depoimento",
  "/admin/",
  "/settings/",
  "/auth/",
  "/private/",
  "/checkout/",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        allow: "/",
        disallow: DISALLOW,
      },
      {
        userAgent: "GPTBot",
        allow: [
          "/",
          "/en",
          "/es",
          "/clinicas",
          "/en/clinicas",
          "/es/clinicas",
          "/plans",
          "/en/plans",
          "/es/plans",
          "/psychologists",
          "/en/psychologists",
          "/es/psychologists",
          "/faq",
          "/en/faq",
          "/es/faq",
          "/about",
          "/en/about",
          "/es/about",
          "/blog",
          "/en/blog",
          "/es/blog",
        ],
        disallow: DISALLOW,
      },
      {
        userAgent: "Google-Extended",
        allow: [
          "/",
          "/en",
          "/es",
          "/clinicas",
          "/en/clinicas",
          "/es/clinicas",
          "/plans",
          "/en/plans",
          "/es/plans",
          "/psychologists",
          "/en/psychologists",
          "/es/psychologists",
          "/faq",
          "/en/faq",
          "/es/faq",
          "/about",
          "/en/about",
          "/es/about",
          "/blog",
          "/en/blog",
          "/es/blog",
        ],
        disallow: DISALLOW,
      },
      {
        userAgent: "PerplexityBot",
        allow: [
          "/",
          "/en",
          "/es",
          "/clinicas",
          "/en/clinicas",
          "/es/clinicas",
          "/plans",
          "/en/plans",
          "/es/plans",
          "/psychologists",
          "/en/psychologists",
          "/es/psychologists",
          "/faq",
          "/en/faq",
          "/es/faq",
          "/about",
          "/en/about",
          "/es/about",
          "/blog",
          "/en/blog",
          "/es/blog",
        ],
        disallow: DISALLOW,
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
