import {
  configureTokenStorage,
  configureSessionFlagStorage,
  createLocalStorageAdapter,
  createSessionStorageFlagAdapter,
  AUTH_STORAGE_KEYS,
  TOKEN_KEY,
  REFRESH_TOKEN_KEY,
  EXPIRES_AT_KEY,
  USER_KEY,
  SESSION_REUSE_WARNING_KEY,
  buildExpiresAt,
  getStoredToken,
  getStoredRefreshToken,
  getStoredExpiresAt,
  getStoredUser,
  getStoredSession,
  persistSession,
  persistAuth,
  persistAuthResponse,
  clearAuth,
  setSessionReuseWarning,
  consumeSessionReuseWarning,
  type AuthSession,
} from "@anima/shared";

configureTokenStorage(createLocalStorageAdapter());
configureSessionFlagStorage(createSessionStorageFlagAdapter());

export {
  AUTH_STORAGE_KEYS,
  TOKEN_KEY,
  REFRESH_TOKEN_KEY,
  EXPIRES_AT_KEY,
  USER_KEY,
  SESSION_REUSE_WARNING_KEY,
  buildExpiresAt,
  getStoredToken,
  getStoredRefreshToken,
  getStoredExpiresAt,
  getStoredUser,
  getStoredSession,
  persistSession,
  persistAuth,
  persistAuthResponse,
  clearAuth,
  setSessionReuseWarning,
  consumeSessionReuseWarning,
  type AuthSession,
};
